### PR TITLE
Typo correction

### PR DESCRIPTION
**Pull request by bipashant**
Added missing full stop '.' on registrations.updated_but_not_signed_in

### CODE REVIEW

**Comment by JasonBarnabe** [comment]
For English, we want to be 100% the same as [what devise has](https://github.com/heartcombo/devise/blob/master/config/locales/en.yml#L47). Please submit a PR to devise to change it, then I'll change it here.

**Comment by JasonBarnabe** [comment]
I decided to be less lazy so I did it: https://github.com/heartcombo/devise/pull/5316

**Comment by bipashant** [comment]
> For English, we want to be 100% the same as [what devise has](https://github.com/heartcombo/devise/blob/master/config/locales/en.yml#L47). Please submit a PR to devise to change it, then I'll change it here.

I have already created Pull Request there.

**Comment by bipashant** [comment]
@JasonBarnabe [heartcombo/devise#5315](https://github.com/heartcombo/devise/pull/5315) has been merged.

**Comment by JasonBarnabe** [comment]
@bipashant Thanks. I'll hold on this PR until the next version of devise, as the tests checks that we match what devise has.

**Comment by JasonBarnabe** [comment]
devise released 4.8.0, this will be in devise-i18n 1.10.0.

**Pull request merged**
