### PR TITLE
Load less locale files

### LINKED ISSUE #117: devise-i18n should only load available locales (if set)
I think it should do [the same thing rais-i18n does](https://github.com/svenfuchs/rails-i18n/blob/master/lib/rails_i18n/railtie.rb). Load only locales in `i18n.available_locales` if set, load every locale otherwise.

Is there's a reason to load everything?

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
This fixes #117 . I've added tests and also tried the patches in one of my apps.

I've also taken the chance to give some love to the gem.

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
Oh, I just notice you're using `Jeweler`, so some of my commits won't play well with it. I'll obviously remove them if you want but I wanted to ask what value `Jeweler` provides (never used it nor heard of it before).

Where out of the 4 places where development dependencies are specified do I need to add `railties`? I'm guessing I need to add it to the `Gemfile` and then regenerate the `gemspec` file with jeweler?

Thanks @tigrish !

**Comment by deivid-rodriguez** [comment]
I updated the PR to use jeweler again.

**Comment by tigrish** [comment]
Sorry @deivid-rodriguez for the delay, I'm just getting back to this now.
I've merged this in to `master` so that it's testable at least.

Since this is a breaking change, I'd like to give it say, a week of testing and then make a major release. :sparkles:

**Comment by tigrish** [comment]
Actually the build fails because the translations have changed, this is the risk!

**Comment by deivid-rodriguez** [comment]
Thanks!

**Pull request merged**
