### PR TITLE
Update views & add simple_form views

### PR DESCRIPTION
**Pull request by pablocrivella**
* Add missing classes to divs
* Switch to new hash syntax
* Remove defaults since these should be loaded form en.yml
* Move generators to a more semantic namespace
```  
rails g devise:i18n:views
rails g devise:i18n:locale
```
* Now if simple_forms is intalled it will generate the
  corresponding views

### CODE REVIEW

**Comment by JasonBarnabe** [comment]
I appreciate the work, but it's really hard to review any changes when you combine multiple changes together into one PR. It seems like every line of the app outside of the translations is changing! Please split these changes out logically into separate PRs.

To address the actual things you're trying to accomplish:
- I would like to maintain the views as close as possible to what devise has. If you're adding the classes to match devise, this is very good.
- New Hash syntax I'm ambivalent about. If devise uses it, then sure, I guess.
- Is there a devise/simple_forms project out there that you're copying from?
- I've had other requests for different view formats - does what you've added make it easy to add more in the future?
- I worry that there's some use case out there for people who don't have en.yml and need the defaults. Not sure why this would be.
- Is there some standard out there for how to name rake tasks?

**Comment by pablocrivella** [comment]
* The changes i made to the views are based on the last version of devise views
* Devise uses new hash syntax
* The simple_form views i copied from devise repo too, also the generator, and i just added the translation keys to those views.
* I think this way is easier to add other view formats than with the way it was before.
* If people don't have the en.yml they are probably not needing translations and they wouldn't need this gem. They could generate views using just devise.
* About the rake tasks standard idk, but now the devise generators looks like this:

````
Devise:
  devise
  devise:controllers
  devise:i18n:locale
  devise:i18n:views
  devise:install
  devise:views
```
Which IMHO has much more sense than before.

And about splitting the changes into more logically separated PR i agree, i wanted to do that at first, this PR was only for the first commit at first, but then i added some more changes to my fork and the PR was automatically update 😅 

Links to devise code y used:

https://github.com/plataformatec/devise/tree/master/lib/generators/templates/simple_form_for
https://github.com/plataformatec/devise/blob/master/lib/generators/devise/views_generator.rb

**Comment by JasonBarnabe** [comment]
So what is actually required to activate the simple_form views? I tried adding `gem 'simple_form', require: 'simple_form'` but it doesn't seem to have made a difference. And whatever the answer is, include the info in the readme.

**Comment by pablocrivella** [comment]
@JasonBarnabe you just need to have simple_forms in your Gemfile, no ```require``` command is needed.
I'll improve the README with this info.

**Comment by JasonBarnabe** [comment]
@pablocrivella were you going to update the readme?

**Comment by pablocrivella** [comment]
Hey @JasonBarnabe, yes! i'll do that later today, i forgot about this 😅

**Comment by pablocrivella** [comment]
@JasonBarnabe i updated the README

**Comment by JasonBarnabe** [comment]
Great, thanks.

**Pull request merged**
