### PR TITLE
Fix all mailer templates for devise4 (fixes #150)

### LINKED ISSUE #150: Email reset_password_token incompatible with devise 4
``` ruby
Devise::VERSION.start_with?('3.') ? @token : @resource.reset_password_token
```

This is not accurate as Devise 4 use @token as well.

### PR DESCRIPTION
**Pull request by rndstr**
Also see #149.

I reverted the condition, otherwise we will have the same issue with 5.x and onwards.

### CODE REVIEW

**Comment by JasonBarnabe** [comment]
This is better that before, but maybe it's better to put this check in a helper or something to avoid duplicating the logic everywhere?

**Comment by rndstr** [comment]
@JasonBarnabe I made an attempt but I'm sorta new to Rails and this is untested. So I'll look at it again over the next few days

**Comment by JasonBarnabe** [comment]
- This fails tests because you're not including view_helpers in lib/devise-i18n.rb.
- `ActionView::Base.send :include, ViewHelpers` could be `ActionView::Base.include, ViewHelpers`. But it may be better to have `Devise::Mailer` include it, because that's the only thing that needs it.
- Any reference to `Devise` means that devise-i18n actually requires Devise. We should formally add this as a dependency or check for its existence.
- `@resource.send("#{type}_token")` can be `@resource.public_send("#{type}_token")`

**Comment by lucascaton** [comment]
Any news on this?

**Comment by lucascaton** [comment]
@rndstr @JasonBarnabe any news on this?
Thanks!

**Comment by rndstr** [comment]
@lucascaton thanks for the ping, I plan on looking at this over the next few days and fixing the things mentioned by @JasonBarnabe

**Comment by rndstr** [comment]
@JasonBarnabe I adjusted according to your feedback :+1: 

> Any reference to Devise means that devise-i18n actually requires Devise. We should formally add this as a dependency or check for its existence.

I agree but not sure how to properly do that. Since `Devise::VERSION` has been in use for a while maybe that could be done in another PR? Or should I add it to the `:development` group in the `Gemfile`?

**Comment by d-schloss-mvg** [comment]
Is there any chance this gets merged some time in the future?

**Comment by JasonBarnabe** [comment]
I forgot about this. I will look at it in the coming days.

I just added devise as a dependency to master, so the `Devise::VERSION` issue is no longer an issue.

**Comment by JasonBarnabe** [comment]
Thanks @rndstr!

**Pull request merged**
