### PR TITLE
Fix typos and some formulation in ru.yml and uk.yml

### PR DESCRIPTION
**Pull request by pixelgoo**
Just a little polish for russian and ukrainian version.

Also I wonder why 'uk' but not 'ua'... doesn't matter though.

### CODE REVIEW

**Comment by JasonBarnabe** [comment]
"uk" is the ISO 639-1 alpha-2 code for Ukrainian (the language). "UA" is the ISO-3166-1 code for Ukraine (the country). See also #172 for a similar question regarding vi/vn.

**Comment by pixelgoo** [comment]
Whoa, didn't know that! Thanks for explanation :+1:

**Comment by tigrish** [comment]
@JasonBarnabe rocks 🤘

**Comment by JasonBarnabe** [comment]
Спасибо and Дякую!

**Pull request merged**
