### PR TITLE
Added Sri Lankan locale lk.yml

### PR DESCRIPTION
**Pull request by roshiend**
added SriLankan (lk) Sinhalese locale

### CODE REVIEW

**Comment by JasonBarnabe** [comment]
Thank you for this. I believe you will need to quote any Sinhalese in double strings. This seems to be required for any non-Latin script. You can see this in for example [the Chinese file](https://github.com/tigrish/devise-i18n/blob/master/rails/locales/zh-CN.yml). This is what Travis is failing on.

Additionally, I think the proper **language code** is `si`. `lk` is the **country code** for Sri Lanka.

**Comment by roshiend** [comment]
thank you for that. I have updated translation hope it works this time.

**Comment by JasonBarnabe** [comment]
There are still some syntax errors in this, but Travis is unhelpful in pointing out where the error is.

- Under the `registrations` key, looks like you accidentally removed `destroyed: `.
- You are missing the closing quotation mark for `send_paranoid_instructions`.

Also, the general rule for naming locales is to not have the country code if there are not significant variations between countries or there is a "default" way of writing the language. If you look at https://github.com/tigrish/devise-i18n/tree/master/rails/locales you can see most do not include the country code. I know nothing of Sinhalese, but if what you are writing would be considered just "Sinhalese" and not "Sinhalese in the special way it is written in Sri Lanka", then I would suggest just having the locale `si`.

**Comment by JasonBarnabe** [comment]
It works now. ඔබට ස්තුතියි!

**Pull request merged**
