### PR TITLE
Translating  'password_change' in pt-BR locale

### PR DESCRIPTION
**Pull request by easybills-admin**

### CODE REVIEW

**Comment by JasonBarnabe** [comment]
Thanks for this. The recommended way to contribute to the translations is to do so on [Locale](https://www.localeapp.com/projects/377). Someone has already provided these translations on there which I've updated in git just now. If you feel the translations can be improved, please make changes on Locale or create a new pull request.

**Comment by easybills-admin** [comment]
No worries, thanks @JasonBarnabe!

**Comment by easybills-admin** [comment]
Will you bump a new version?

Cheers.

**Comment by JasonBarnabe** [comment]
1.0.1 is out.

**Comment by easybills-admin** [comment]
@JasonBarnabe thanks! :smile:

**Pull request closed without merging**
