### PR TITLE
Fix typo in de.yml

### PR DESCRIPTION
**Pull request by Jay-Schneider**
Add missing comma before "um".

More details why the comma is needed there can be found here for example: https://www.sprachschach.de/komma-vor-um/

### CODE REVIEW

**Comment by JasonBarnabe** [comment]
Danke!

**Comment by Jay-Schneider** [comment]
No thank you for your quick reaction @JasonBarnabe  😉

I assume this change will be included in any future release (read `>= 1.9.3`?) – can you estimate when this will happen?

**Comment by JasonBarnabe** [comment]
Yes, it will be included in the next release. I usually do them every few months, which I guess means one is overdue...

**Comment by Jay-Schneider** [comment]
Thanks for the effort! ☺️

**Pull request merged**
