### PR TITLE
Reworking sq translation

### PR DESCRIPTION
**Pull request by ujdhesa**
Hello,

I'm submitting a reworked version for this resource. The current one is a bit awkward, due to avoidable transliterations and transcriptions (_konfirmim_, _tokeni_, _llogim_, _enkriptim_, _enkriptuar_, _lloguar_, _resetim_, _valid_, _link_, _autentifikojmë_  - all missing from the corpus of sq), conceptual errors ( locking vs blocking, receving an email vs accepting an email, attempt vs chance), and some typos. Some wording was seen necessary to make the translation flow better under sq's musicality. 
Please pull it into the master.

Regards,
Besnik

### CODE REVIEW

**Comment by JasonBarnabe** [comment]
Thanks for the suggestions. It looks like you introduced some syntax errors in the file. In particular, the quotes you removed on line 42 were necessary. Please retain quotations wherever they were previously and then we'll see if it works.

**Comment by ujdhesa** [comment]
> Thanks for the suggestions. It looks like you introduced some syntax errors in the file. In particular, the quotes you removed on line 42 were necessary. Please retain quotations wherever they were previously and then we'll see if it works.

I just checked the original en.yml and there's no quotes around that string. A quick check of sq.yml against en.yml shows that all "" in en.yml were respected. 
Idem for '' quotes.

So it looks like I haven't introduce any syntax error. 

A quick look through Meld of the two files shows no errors in the structure of the file. It has an identical to that of en.yml.

TIA

**Comment by JasonBarnabe** [comment]
You can see the error in the Travis build referenced in this PR.

The English file does not error without the quotes on that string because it does not start with a special character (`%`) in English.

**Comment by ujdhesa** [comment]
Thank you, Jason!

**Comment by JasonBarnabe** [comment]
Faleminderit!

**Pull request merged**
