### PR TITLE
Update Gemfile.lock and add mailer template

### PR DESCRIPTION
**Pull request by yhirano55**
I have done these:

* Update Gemfile.lock after `bundle update`.
* Add mailer template for password_change.
* Update ja and zh-TW locale

---

I have removed this commit:

* Add gem i18n-tasks on development only Ruby >= 2.1.

## About i18n-tasks

I think really useful gem. Please see: * [glebm/i18n-tasks](https://github.com/glebm/i18n-tasks)

## Purpose of install this gem

Fix all missing keys and be easy to maintain all locale files.

## Available tasks

* find missing keys: `bundle exec i18n-tasks missing`
* find missing keys and filling value in base locale (en): `bundle exec i18n-tasks add-missing`
* normalize keys (sorting a-z) all locale files: `bundle exec i18n-tasks normalize`
* If it found missing keys, spec will be failure: `bundle exec rspec spec/i18n_spec.rb`

## Next step

* We should fill (or translate) all missing keys: `bundle exec i18n-tasks add-missing`.
* Enable pending example `spec/i18n_spec.rb`.

### CODE REVIEW

**Comment by JasonBarnabe** [comment]
In the future, please limit your pull requests to one topic at a time unless there's a compelling reason to combine them.

- Update Gemfile.lock after bundle update. :white_check_mark: 
- Add mailer template for password_change. :white_check_mark: 
- Update ja and zh-TW locale. :white_check_mark: 
- Add gem i18n-tasks on development only Ruby >= 2.1. :question: 

I don't understand what benefit i18n-tasks provides over top of the current recommendation to translate on [Locale](https://www.localeapp.com/projects/377). I also don't know why you would want to add in the base strings to the locale files - in my experience Rails handles this for you.

**Comment by yhirano55** [comment]
Thanks for comment. I'll remove the commit `Add gem i18n-tasks on development only Ruby >= 2.1` in this PR and send this again.

---

But ... let me explain about `i18n-tasks`.

`i18n-tasks` gem that is used by [rails-i18n](https://github.com/svenfuchs/rails-i18n) provides that it makes it easy to maintain all locale files ( especially we can find untranslated keys. And it can fill these keys in English (base).

for example of workflow:

1: Add a new line in english

```yaml
en:
  greeting: Hello
  message: world # << add this line
```

```yaml
ja:
  greeting: こんにちは
```

^ When it have many untranslated keys, it's not easy to find it for us.

2: Find missing keys in Japanese: `bundle exec i18n-tasks missing`

```shell
$ bundle exec i18n-tasks missing
+--------+---------+----------------------------------+
| Locale | Key     | Value in other locales or source |
+--------+---------+----------------------------------+
| ja     | message | en world                         |
+--------+---------+----------------------------------+
```

3: Fill missing keys in English: `bundle exec i18n-tasks add-missing`

```yaml
ja:
  greeting: こんにちは
  message: world # << add this line
```

^ With filling missing keys in English, All maintainers can find untranslated keys easily.

4: It's translated to their languages from English by all maintainers.

**Comment by JasonBarnabe** [comment]
That sounds like it conflicts with how Locale does it (empty string means untranslated content), so I think it should not be implemented.

**Comment by yhirano55** [comment]
I have understood, thanks.

**Pull request merged**
