### PR TITLE
Fixed word ending for RU

### PR DESCRIPTION
**Pull request by printercu**
Changed
```
E-mail уже подтверждена -> E-mail уже подтверждён
E-mail не найдена -> E-mail не найден
```

### CODE REVIEW

**Comment by printercu** [comment]
I've also added some new attributes and tests are failing now. This attrs are used in https://github.com/plataformatec/devise/blob/69bee06ceee6280b54304928bb6e55c5064abad8/lib/devise/models/recoverable.rb#L143
and confirmable.rb

**Comment by JasonBarnabe** [comment]
Those two new attributes are potentially used in the UI somewhere?

**Comment by printercu** [comment]
`reset_password_token` is shown in the reset password form, when link is expired: `Reset password token устарела. Пожалуйста, запросите новую`.

Seems like I've found before the place, where `:unconfirmed_email` is used within error, but can't reproduce it now. Maybe I've just missing something.

**Comment by printercu** [comment]
I've found same for `unlock_token`: `Unlock token имеет неверное значение` when user is not locked/already unlocked. Should I add this translation?

**Comment by JasonBarnabe** [comment]
If it's something that can come up in the UI, then it should be added. It's probably just missing because these are uncommon errors.

**Comment by printercu** [comment]
Yep, I've found then when was testing the whole flow. I'll add little bit later. What about tests? Should I fix em?

**Comment by JasonBarnabe** [comment]
You can fix them if you want, I was just going to fix them myself if not. I think all that's needed is adding the strings to the English file as well.

**Comment by printercu** [comment]
I'll try. Seems like I can just add this translations to en locale.

**Comment by printercu** [comment]
Fixed. I've translated `reset_password_token` as `Reset password link`, so that error msg `Reset password link has expired, please request a new one` is more human-readable.

**Comment by JasonBarnabe** [comment]
I think devise will just call it "Reset password token", so leave it as that. We're not here to second-guess devise's English :)

**Comment by printercu** [comment]
Devise doesn't translate it. Ok, I'll change.

**Pull request merged**
