### PR TITLE
Fixed incorrect value

### PR DESCRIPTION
**Pull request by Lomey**
Fixed incorrect omniauth_callbacks: failure: value

### CODE REVIEW

**Comment by JasonBarnabe** [comment]
What makes it incorrect? The quoting is the same as in the original.

**Comment by Lomey** [comment]
No, look more carefuly(point in the end of the 75 row).
https://github.com/tigrish/devise-i18n/pull/236/commits/433a116a8433c3efb5adff01e07caaf94ce225fb
Btw original yaml is unreadable for `YAML.load_file('file_right_path.yml')`

**Comment by JasonBarnabe** [comment]
If periods are supposed to be outside quotations in a case like this in Ukrainian, then the current code is correct. If periods are supposed to be inside quotations, then it should be:
```
      failure: Ви не можете увійти в систему обліковим записом %{kind}, тому що "%{reason}."
```
Your change is also changing the position of the open quotation mark. The entire string does not need to be quoted. The file is valid as-is.

**Comment by Lomey** [comment]
I can not reproduce this issue again because I forgot the case when it raise, so when I put the dot (which at the end of the row) before close quotation mark and make entire string quoted (that is all what I have changed), issue has gone.

Excuse me if I did something wrong

**Pull request closed without merging**
