### PR TITLE
Bangla translation for Devise

### PR DESCRIPTION
**Pull request by maruf-freelancer**
Please merge this pull request for Bangla translation of devise locale for Bangladesh.

### CODE REVIEW

**Comment by tigrish** [comment]
Hi @maruf-freelancer, the build is failing because the top level namespace of your yaml file is `en:` whereas I'm sure you meant to put `bn:` - can you update this pull request?

**Comment by maruf-freelancer** [comment]
Thanks. I have updated the namespace to bn

**Comment by tigrish** [comment]
Cool, would you care to complete these translations? https://www.localeapp.com/projects/377/translations?in_locale=25883&state=incomplete

**Comment by maruf-freelancer** [comment]
I have updated in localapp. What should I do next? How to update in github too?

**Comment by tigrish** [comment]
I have just bumped it myself - thanks for contributing!

**Pull request merged**
