### PR TITLE
Update Czech translation

### PR DESCRIPTION
**Pull request by jonatanklosko**
Credits to Christine Vasta (@kiwiistnichtda) =)

### CODE REVIEW

**Comment by JasonBarnabe** [comment]
Dík!

Note that this translation is currently at 97% and only 3 strings remain. If it makes it easier, you can also translate at https://www.localeapp.com/projects/377

**Comment by jonatanklosko** [comment]
@JasonBarnabe Thanks! Christine used our own tool to update the translation, but I see the pluralization is handled a bit differently, so it makes sense to just use Localapp anyway. I've just asked her for translating the remaining phrases =)

**Comment by jonatanklosko** [comment]
Hey @JasonBarnabe, Christine has translated the remaining phrases using Localeapp. Any way for this being released somehow soon? =)

**Comment by kiwiistnichtda** [comment]
Hey!

Any news on releasing the modified translation?

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Bez
virů. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2018-02-26 14:07 GMT+01:00 Jonatan Kłosko <notifications@github.com>:

**Comment by JasonBarnabe** [comment]
It was released yesterday in 1.6.1.

**Comment by jonatanklosko** [comment]
@JasonBarnabe Lovely, thanks a lot! :tada: 

@kiwiistnichtda Thanks for the reminder, I'll update our website to the latest version soon!

**Pull request merged**
