### PR TITLE
Update zh-CN translations

### PR DESCRIPTION
**Pull request by SerCom-KC**

### CODE REVIEW

**Comment by SerCom-KC** [comment]
Hmm, looks like si-LK is blocking me...

**Comment by JasonBarnabe** [comment]
si-LK.yml was added by mistake. Should be no problems now.

@johnnyshields did you want to have your people review these changes (or any changes where your people previously reviewed the translations)?

**Comment by JasonBarnabe** [comment]
谢谢！

**Comment by johnnyshields** [comment]
This is fine but would be nice if we can keep zh-TW / zh-HK in sync.

**Pull request merged**
